<?php
/**
 * MageWorx
 * Admin Order Editor extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersEdit
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<div class="entry-edit">
    <div class="fieldset">
        <?php echo $this->getForm()->toHtml() ?>
    </div>
</div>
<script type="text/javascript">
    VatParameters.groupIdHtmlId = <?php echo $this->getCustomer()->getGroupId(); ?>;
</script>