<?php
/**
 * MageWorx
 * Admin Order Editor extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersEdit
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<div class="ordersedit-buttons">
    <button class="f-left" type="button" title="<?php echo $this->__('Cancel') ?>" onclick="orderEdit.cancel()">
        <span><span><?php echo $this->__('Cancel') ?></span></span>
    </button>
    <button class="f-right" type="button" title="<?php echo $this->__('Submit') ?>" onclick="orderEdit.saveOrder()">
        <span><span><?php echo $this->__('Submit') ?></span></span>
    </button>
</div>