<?php
/**
 * MageWorx
 * Admin Order Editor extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersEdit
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>

<?php $_shippingRateGroups = $this->getShippingRates(); ?>

<?php if ($this->getQuote()->isVirtual()): ?>
    <div>
        <span><?php echo $this->__('Shipping method selection is not applicable') ?></span>
    </div>
<?php elseif ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" style="display:none">
        <dl class="shipment-methods">
            <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt><strong><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></strong></dt>
                <dd>
                    <ul>
                        <?php foreach ($_rates as $_rate): ?>
                            <?php $_radioProperty = 'name="shipping[shipping_method]" type="radio"' ?>
                            <?php $_code=$_rate->getCode() ?>
                            <li>
                                <?php if ($_rate->getErrorMessage()): ?>
                                    <ul class="messages">
                                        <li class="error-msg"><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li>
                                    </ul>
                                <?php else: ?>
                                    <?php $_checked = $this->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                                    <input <?php echo $_radioProperty ?> value="<?php echo $_code ?>" id="s_method_<?php echo $_code ?>" <?php echo $_checked ?>/>
                                    <label class="normal" for="s_method_<?php echo $_code ?>">
                                        <?php echo $this->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?> -
                                        <strong>
                                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                                            <?php echo $_excl; ?>
                                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                            <?php endif; ?>
                                        </strong>
                                    </label>
                                <?php endif ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
        </dl>
    </div>
    <?php if ($_rate = $this->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info">
            <strong><?php echo $this->escapeHtml($this->getCarrierName($_rate->getCarrier())) ?></strong> -
            <?php echo $this->escapeHtml($_rate->getMethodTitle() ? $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?>
            <br />

            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
            <?php $customPrice = Mage::getSingleton('adminhtml/session_quote')->getShippingCustomPrice(); ?>
            <?php $shippingPrice = ($customPrice > 0) ? $customPrice : $_rate->getPrice(); ?>

            <label for="shipping_price"><?php echo $this->__('Price'); ?>: </label>
            <input type="text" name="shipping[custom_price]" id="shipping_price" value="<?php echo $shippingPrice ?>" />

            <br/>
            <a href="#" onclick="$$('#order-shipping-method-info').each(function(el){ el.hide() });$('order-shipping-method-choose').show();$('shipping_price').remove();return false">
                <?php echo Mage::helper('sales')->__('Click to change shipping method') ?>
            </a>
        </div>
    <?php else: ?>
        <script type="text/javascript">$('order-shipping-method-choose').show();</script>
    <?php endif; ?>
<?php else: ?>
    <strong><?php echo Mage::helper('sales')->__('Sorry, no quotes are available for this order at this time.') ?></strong>
<?php endif; ?>