<div class="searchindex-result">
    <?php echo $this->getPager() ?>
    <ul>
        <?php foreach($this->getCollection() as $_item) : ?>
        <li>
            <div class="title">
                <a href="<?php echo $_item->getArticleUrl() ?>"><?php echo $_item->getTitle() ?></a>
            </div>
            <div class="content">
                <?php echo Mage::helper('core/string')->truncate(strip_tags($_item->getData('kb_article_content')), 300) ?>
            </div>
        </li>
        <?php endforeach ?>
    </ul>
    <?php echo $this->getPager() ?>
</div>