<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Checkoutfees
 */
?>
<?php if ($this->getFees() && is_array($this->getFees())) { ?>
    <div class="shipping gift-messages amcheckoutfees block">
        <h2><?php echo Mage::helper('amcheckoutfees')->__('Checkout Fees'); ?></h2>

        <div class="discount-form" id="amcheckoutfees_form_block">
            <form id="amcheckoutfees_form" method="post" action="<?php echo Mage::getUrl('amcheckoutfees/index/saveFormData'); ?>">
                <ul>
                    <?php foreach ($this->getFees() as $feeId => $feeData) { ?>
                        <?php $fee = $feeData['fee'];
                        $options   = $feeData['options']; ?>
                        <li>
                            <label for="<?php echo $fee->getFeesId(); ?>"><?php echo $fee->getTitleForStore(); ?></label>
                            <?php if ($fee->getDescription()) { ?>
                                <a href="#" class="amcheckoutfees-tooltip link-store-scope"
                                   data-tooltip="<?php echo htmlspecialchars($fee->getDescription()); ?>"></a>
                            <?php } ?>
                            <br/>
                            <?php if ($options && is_array($options)) { ?>
                                <?php echo Mage::helper('amcheckoutfees')->renderFeeOptions($fee, $options); ?>
                            <?php } ?>
                        </li>
                    <?php } ?>
                </ul>
                <br/>
                <?php if (Mage::app()->getRequest()->getModuleName() == 'checkout' && Mage::app()->getRequest()->getControllerName() == 'cart') { ?>
                    <div class="checkout-types bottom">
                        <button type="submit" title="<?php echo Mage::helper('amcheckoutfees')->__('Apply'); ?>" id="amcheckoutfees_apply_changes1"
                                class="button"><span><span><?php echo Mage::helper('amcheckoutfees')->__('Apply'); ?></span></span></button>
                    </div>
                <?php } ?>
            </form>
        </div>
    </div>
<?php } ?>
<script>
    var amcheckoutfees_base_url = '<?php echo Mage::app()->getStore()->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);?>';
</script>