<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Checkoutfees
 */
?>
<?php echo $this->getChildHtml('amcheckoutfees_shipping', '', true, true) ?>

<?php if (!$this->getQuote()->isVirtual()): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif; ?>