<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Checkoutfees
 */
?>
<?php /** @var $this Amasty_Checkoutfees_Block_Checkout_Onepage_Payment_Additional */ ?>


<?php if ($fees = $this->getFees('payment')) { ?>
    <div class="checkout-onepage-payment-additional-checkoutfees-payment" id="checkoutfees_payment">
        <h2><?php echo Mage::helper('amcheckoutfees')->__('Checkout Fees'); ?></h2>

        <div class="discount-form" id="amcheckoutfees_payment_form_block">
            <form id="amcheckoutfees_payment_form" method="post" action="<?php echo Mage::getUrl('amcheckoutfees/index/saveFormData'); ?>">
                <ul>
                    <?php foreach ($fees as $feeId => $feeData) { ?>
                        <?php
                        $fee     = $feeData['fee'];
                        $options = $feeData['options'];
                        if ($fee->getAutoapply()) {
                            continue;
                        }
                        ?>
                        <li>
                            <label for="<?php echo $fee->getFeesId(); ?>"><?php echo $fee->getTitleForStore(); ?></label>
                            <?php if ($fee->getDescription()) { ?>
                                <a href="#" class="amcheckoutfees-tooltip link-store-scope"
                                   data-tooltip="<?php echo htmlspecialchars($fee->getDescription()); ?>"></a>
                            <?php } ?>
                            <br/>
                            <?php if ($options && is_array($options)) { ?>
                                <?php echo Mage::helper('amcheckoutfees')->renderFeeOptions($fee, $options); ?>
                            <?php } ?>
                        </li>
                    <?php } ?>
                </ul>
                <br/>
                <?php if (Mage::app()->getRequest()->getModuleName() == 'checkout' && Mage::app()->getRequest()->getControllerName() == 'cart') { ?>
                    <div class="checkout-types bottom">
                        <button type="submit" title="<?php echo Mage::helper('amcheckoutfees')->__('Apply'); ?>" id="amcheckoutfees_apply_changes"
                                class="button"><span><span><?php echo Mage::helper('amcheckoutfees')->__('Apply'); ?></span></span></button>
                    </div>
                <?php } ?>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        //<![CDATA[
        try {
            if (payment) {
                function initCheckoutPaymentFees() {
                    if ($$('#amcheckoutfees_payment_form_block input')) {
                        try {
                            $$('#amcheckoutfees_payment_form_block input').each(function (el) {
                                try {
                                    el.writeAttribute("disabled", false);
                                } catch (e) {
                                    console.log('CheckoutFees: no payment Input to enable');
                                }
                            });
                        } catch (e) {
                            console.log('CheckoutFees: no payment Input to look through');
                        }
                    }
                    if ($$('#amcheckoutfees_payment_form_block select')) {
                        try {
                            $$('#amcheckoutfees_payment_form_block select').each(function (el) {
                                try {
                                    el.writeAttribute("disabled", false);
                                } catch (e) {
                                    console.log('CheckoutFees: no payment Select to enable');
                                }
                            });
                        } catch (e) {
                            console.log('CheckoutFees: no payment Select to look through');
                        }
                    }
                }

                payment.addAfterInitFunction('amCheckoutPaymentFeesInit', initCheckoutPaymentFees);


                Payment.prototype.clickCheckoutFeesInput = function () {
                    if (!payment.switchMethod()) {
                        if (typeof updateCheckout === "function") {
                            updateCheckout('payment_method');
                        }
                    }
                };

                $('amcheckoutfees_payment_form_block').on('change', 'input', function (event) {
                    payment.clickCheckoutFeesInput();
                });
                $('amcheckoutfees_payment_form_block').on('change', 'select', function (event) {
                    payment.clickCheckoutFeesInput();
                });
            }
        } catch (e) {
            console.log('CheckoutFees: cannot load payment');
        }
        //]]>
    </script>
<?php } ?>