<?php
/**
 * MagPassion_Quickview extension
 * 
 * @category   	MagPassion
 * @package		MagPassion_Quickview
 * @copyright  	Copyright (c) 2014 by MagPassion (http://magpassion.com)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
    <base target="_parent" />
</head>
<body class="page-empty <?php echo $this->getBodyClass()?$this->getBodyClass():'' ?>">
    <div>
        <div class="mp_quickview_product_page">
            <?php echo $this->getChildHtml('content') ?>
        </div>
    </div>
</body>
</html>
