<?php
	if (Mage::getStoreConfig('pdp/setting/enable') == 0) {
		echo "<h3>".$this->__('PDP module is disabled. Please enable PDP to use it\'s features!')."</h3>";
		return false;
	}
    $productId = $this->getCurrentProductId();
    $product = Mage::getModel('catalog/product')->load($productId);
    $title = $product->getName();
	$viewMode = $this->getViewMode();
	$jsonString = $this->getJsonContentFromParam();
	if ($jsonString == "") {
		if ($viewMode == "backend") {
			$jsonString = $this->_helper->getAdminTemplates($productId);
		} else {
			if($this->getShareId() != null) {
				$jsonString = $this->_helper->getShareJsonString($this->_shareId);
			} else {
				$jsonString = $this->_helper->getAdminTemplates($productId);
			}
		}	
	}
?>
<div class='design-btn' style="display: none">
	<?php echo $this->getLayout()->createBlock('pdp/designbutton')->setTemplate('pdp/product/design_button.phtml')->toHtml() ?>
</div>
<input name="pdp_design_string" type="hidden" value="<?php echo htmlentities($jsonString) ?>"/>
<?php echo $this->getChildHtml('design_top_bar'); // Design Area Topbar (Product Title, Save, Download, Sharing) ?>
<div class="wrap_pdp_design">
	<?php echo $this->getChildHtml('product_side'); // Product Sides ?>
	<div class="pdc-design-area"> 
		<div class="pdc-design-area-left">
			<?php echo $this->getChildHtml('design_main'); //Main Design Area ?>
		</div>
		<div class="pdc-design-area-right">
			<?php echo $this->getChildHtml('design_tabs'); // Design Tabs (Add photo, Add Text, Quote, Layer ?>
		</div>
	<?php echo $this->getChildHtml('hidden_popups'); // All Hidden Actions popup ?>
    <?php echo $this->getChildHtml('layer'); ?>
</div>
</div>

<?php /* ===NEVER CHANGE ID/CLASS == */ ?>
<div id="img_sessiton" class="nodisplay"></div>
<img alt="" id="temp_inlay_image" src="" style="display: none;"/>
<img alt="" id="temp_final_image" src="" style="display: none;"/>
<input id="temp_action" type="hidden" value=""/>
<div class="temp_container" style="display: none;"></div>
<?php $js_pdp = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'pdp/'; ?>
<!-- Preview / Download Popup -->
<div id="pdp_design_popup"></div>
<div class='pdp_actions_backend'>
	<?php if ($this->isAdminUser()) : ?>
	<input type="hidden" id="is_backend" value="yes" />
	<link href="<?php echo $js_pdp;?>bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>bootstrap/3.3.4/css/bootstrap-theme.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.pips.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/mcustomscrollbar/jquery.mcustomscrollbar.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>material-icons/style.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pace/dataurl.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/jcrop/jquery.jcrop.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/pdc.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/pdc.layer.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/iframe.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/colorpicker/css/colorpicker.css" rel="stylesheet"/>
	<script src="<?php echo $js_pdp;?>jquery/jquery-1.10.2.min.js"></script>
	<script src="<?php echo $js_pdp;?>bootstrap/3.3.4/js/bootstrap.min.js"></script>
	<script src="<?php echo $js_pdp;?>pace/pace.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.all.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/mcustomscrollbar/jquery.mcustomscrollbar.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/jcrop/jquery.jcrop.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/ui/jquery-ui.min.js"></script>
	<script src="<?php echo $js_pdp;?>fabricjs/fabric-1.5.0.min.js"></script>
	<script src="<?php echo $js_pdp;?>pdc/js/draggabilly.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/colorpicker/colorpicker.js"></script>
	<?php endif; ?>
</div>

<div id="pdp_info_to_action" class="nodisplay">
    <input type="hidden" value="<?php echo (isset($_REQUEST['fb'])) ? $_REQUEST['fb'] : "";  ?>" id="fb_get_id" />
    <input type="hidden" value="<?php echo $product->getProductUrl(); ?>" id="current_url" />
    <input type="hidden" id="product_id" name="product_id" value="<?php echo $productId; ?>" />
    <input type="hidden" value="<?php echo $this->getSkinUrl('pdp/') ?>" id="skin_url" />
	<input type="hidden" id="base_dir" name="base_dir" value="<?php echo Mage::getBaseDir('base'); ?>" />
	<input type="hidden" id="is_editable" name="is_editable" value="yes" />
	<input type="hidden" id="pdp_media_url" name="pdp_media_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/'; ?>" />
	<input type="hidden" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK).Mage::getStoreConfig('pdp/setting/urlkey'); ?>" id="pdp_uri_key" />
</div>
<script src="<?php echo $js_pdp;?>pdc/js/productsdesignercanvas-1.0.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc.layer.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc1.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc2.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/script.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/startup.js"></script>
