<?php
/**
 * MageWorx
 * Admin Order Editor extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersEdit
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */

if ($this->getSource()->getOrdersEditFlag()) { ?>
<tr>
    <td class="label" colspan="2" style="color:#EB5E00;">
        <?php echo Mage::helper('mageworx_ordersedit')->__("Note: order's initial Grand Total value to be captured unless credit card info is re-submitted") ?>
    </td>    
</tr>
<?php } ?>