<?php 
$shareId = $this->getRequest()->getParam("share");
if (!$shareId) {
	return;
}
$sampleImages = $this->helper("pdp")->getShareThumbnail($shareId);
?>
<?php foreach($sampleImages as $image) : ?>
<?php // inlay contain width and height of overlay image. Same side as png export when share ?>
<?php $imageSize = explode(",", $image['inlay']); ?>
<link og:image="<?php echo $image['image'] ?>" rel="image_src" href="<?php echo $image['image'] ?>"/>
<!--For facebook share. First time share should show the thumbnail-->
<meta property="og:image" content="<?php echo $image['image'] ?>"/>
<meta property="og:image:width" content="<?php echo $imageSize[0] ?>" />
<meta property="og:image:height" content="<?php echo $imageSize[1] ?>" />
<!--End Facebook share setting-->
<?php endforeach; ?>
