<div class="col2-set">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Contact Information') ?></h3>
                <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
                    <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
                    <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
                </p>
            </div>
        </div>
    </div>
    <?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Newsletters') ?></h3>
                <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
            </div>
            <div class="box-content">
                <p>
                    <?php if (!Mage::helper('ngroups')->isManagementAllowed()):?>
                        <?php if( $this->getIsSubscribed() ): ?>
                            <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                        <?php else: ?>
                            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php 
                        $subscriberId = Mage::helper('ngroups')->getSubscriberIdByEmail(Mage::getSingleton('customer/session')->getCustomer()->getEmail());
                        $groups = Mage::getModel("ngroups/ngroups")->getSubscriberGroups($subscriberId, false, true);
                        ?>
                        <?php if (sizeof($groups)):?>
                            <?php echo $this->__('You are currently subscribed to newsletters:') ?><br />
                            <ul>
                            <?php
                            foreach($groups as $group){
                                $group = Mage::getModel("ngroups/ngroups")->load($group->getGroupId());
                                ?>
                                    <li><?php echo $group->getTitle()?></li>   
                                <?php
                            }
                            ?>
                            </ul>
                        <?php else: ?>
                            <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                        <?php endif;?>
                    <?php endif;?>
                </p>
            </div>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
    </div>
    <?php endif; ?>
</div>
