<?php if(Mage::getStoreConfig('pdp/customer_action/is_facebook')){ ?>
<div class="modal fade" id="facebookPhotos" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title"><i class="pdc-facebook-square"></i> <?php echo $this->__('My Facebook Photo');?></h4>
	  </div>
	  <div class="modal-body">
			<?php $facebookInfo = $this->getFacebookInfo();
				if (is_array($facebookInfo)) {
					$facebookAppId = $facebookInfo['facebook_app_id'];
					$facebookKey = $facebookInfo['facebook_secret_key'];
				}
			?>
			<?php if(isset($facebookInfo['facebook_app_id']) && $facebookInfo['facebook_app_id'] != ''){ ?> 
			   <a  title="<?php echo $this->__('Facebook'); ?>" tab-content="content_facebook" class="facebook_api"><?php echo $this->__('Facebook'); ?></a>
			<?php } ?>
		<div class="content_facebook nodisplay" pdc-clipart-tab="content_facebook">
			  <div id="fb-root"></div>
			  <div id="user-info"></div>
			  <div id="photos_album"></div>
			  <button id="fb-auth" class=" upload_photo_btn fb_photo_btn " type="button"><i class="pdc-facebook-square"></i> <?php echo $this->__('Login To My Facebook');?></button>
		</div>
	  </div>
	</div> 
  </div>
</div>
<?php } ?>