<!-- Modal uploadPhotos-->
<?php $helper = $this->helper("pdp/upload"); ?>
<div class="modal fade" id="uploadPhotos" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title"><i class="pdc-file-upload"></i> <?php echo $this->__('Upload Files');?> </h4>
	  </div>
	  <div class="modal-body">
		<p style="text-align:center;"><?php echo $this->__('By uploading an image you guarantee that you have read these <strong>Terms &amp; Conditions</strong> of Uploading Photos.<br/>And that you agree to abide by all clauses within these <strong>Terms and Conditions</strong>.');?></p>
		<div class="content_upload nodisplay" pdc-clipart-tab="content_upload">
			<!--Uploaded Image Here-->
            <?php $customImageInSession = Mage::getSingleton("core/session")->getCustomUploadImages(); ?>
            <div id="lists_img_upload">
				<div class="row">
				<?php if (is_array($customImageInSession) && count($customImageInSession) > 0) : ?>
					<?php //echo "<pre>"; print_r($customImageInSession); ?>
					<?php foreach($customImageInSession as $_customImg) : ?>
					<div class="col-sm-6 col-md-4">
						<div class="thumbnail" pdc-data="upload-item">
							<img pdc-data="upload-image" width="130px" alt="Invalid Image" src="<?php echo $_customImg ?>" color="">
							<div class="caption" style="text-align: center;">
								<p>
									<a class="btn btn-default crop-item" role="button"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> <?php echo $this->__("Crop") ?></a>
									<a class="btn btn-default add-to-design" role="button"><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> <?php echo $this->__("Add To Design") ?></a>
								</p>
							</div>
						</div>
					</div>
					<?php endforeach; ?>
				<?php endif; ?>
				</div>
			</div>
            <?php $uploadImageAction = Mage::getBaseUrl() . "pdp/upload/uploadCustomImage" ?>
			<form id="upload_images_form" action="<?php echo $uploadImageAction ?>" method="POST" enctype="multipart/form-data">
                <input type="hidden" id="pdc_upload_config" value="<?php echo htmlentities($helper->getConfig('JSON')) ?>"/>
				<div class="row">
                    <div class="col-sm-12 pdc-message">
                        <?php if($helper->getUploadNote() != "") : ?>
                        <div id="msg_info" class="alert alert-info" role="alert">
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                            <?php echo $helper->getUploadNote() ?>
                        </div> 
                        <?php endif; ?>
                        <div id="msg_error" class="alert alert-danger hide" role="alert">
                            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                            <span class="message"></span>
                        </div>
                        <div id="msg_success" class="alert alert-success hide" role="alert">
                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                            <span class="message"></span>
                        </div>
					</div>
                    <div class="col-sm-3">
                        <div class="file-upload">
                            <span class="btn btn-md btn-primary btn-file">
                                <i class="glyphicon glyphicon-file "></i>
                                <?php echo $this->__('Browse') ?> ... <input type="file" accept="image/*" name="uploads[]" id="fileToUpload" class="upload_photo" />
                            </span>
                            <button id="upload_custom_img_btn" class="btn btn-success" type="button" name="upload_custom_img_btn"><?php echo $this->__('Upload') ?></button>
                        </div>
                    </div>
                    <div class="col-sm-9">
                        <div class="progress" style="display: none;">
                            <div class="progress-bar " role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                0%
                             </div>
                        </div>
                    </div>
                </div>
			</form>
		</div>
	  </div>
	</div>
  </div>
</div>
<!--New Crop Modal-->
<div id="crop_modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?php echo $this->__("Crop Area") ?></h4>
          </div>
          <div class="modal-body">
            <div id="crop_panel">
                <img id="crop_image" src=""/>
            </div>
          </div>
          <div class="modal-footer">
              <a pdc-action="crop-image" class="btn btn-info"><?php echo $this->__("Crop") ?></a>
              <a pdc-action="cancel-crop" class="btn btn-warning"><?php echo $this->__("Cancel") ?></a>
          </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


