<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
<style type="text/css">
    html,body { height:100%; }
</style>
</head>
<?php $_queue = Mage::registry('current_model') ?>
<body id="html-body" style="background:#fff;">
<div id="preview" class="cms-revision-preview">
    <div class="toolbar">
        <div class="switcher">
            <table cellspacing="10px">
                <tr>
                    <th>Sender:</th>
                    <td><?php echo $_queue->getSenderName() ?> (<?php echo $_queue->getSenderEmail() ?>)</td>
                </tr>
                <tr>
                    <th>Recipient:</th>
                    <td><?php echo $_queue->getRecipientName() ?> (<?php echo $_queue->getRecipientEmail() ?>)</td>
                </tr>
                <tr>
                    <th>Subject:</th>
                    <td><?php echo $_queue->getSubject() ?></td>
                </tr>
            </table>
        </div>
    </div>
    <iframe name="preview_iframe" id="preview_iframe" frameborder="0"></iframe>
    <?php echo $this->getChildHtml('preview_form'); ?>
</div>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>

<script type="text/javascript">
//<![CDATA[
var previewForm = $('preview_form');
var loadingMask = $('loading-mask');
var previewIframe = $('preview_iframe');

function preview() {
    previewForm.writeAttribute('target', previewIframe.readAttribute('id'));
    blockPreview();
    previewForm.submit();
}

function blockPreview() {
    var cumulativeOffset = $('preview').cumulativeOffset();
    $('loading-mask').setStyle({
        top:  ( cumulativeOffset.top ) + 'px',
        left: ( cumulativeOffset.left ) + 'px',
        width: $('preview').getWidth() + 'px',
        height: $('preview').getHeight() + 'px'
    });

    toggleSelectsUnderBlock($('loading-mask'), false);
    Element.show('loading-mask');
    setLoaderPosition();
}

function unBlockPreview() {
    toggleSelectsUnderBlock(loadingMask, true);
    Element.hide(loadingMask);
}

Event.observe(window, 'load', preview);
Event.observe(previewIframe, 'load', unBlockPreview);
//]]>
</script>
</body>
</html>
