<!-- Modal Download Popup -->
	<div class="modal fade" id="downloadPopup" tabindex="-1" role="dialog" aria-hidden="true">
	  <div class="modal-dialog modal-md">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title"><?php echo $this->__('Download customized design'); ?></h4>
		  </div>
		  <div class="modal-body">
			<button class="btn btn-md btn-primary" pdc-data="pdc-btn" pdc-action="DOWNLOAD_AS_IMAGE"><?php echo $this->__('Save as photo');?></button> | <button class="btn btn-md btn-primary" pdc-data="pdc-btn" pdc-action="DOWNLOAD_AS_PDF"><?php echo $this->__('Save as PDF');?></button> 
		  </div>
		</div>
	  </div>
	</div>