<?php 
$productConfigs = $this->getProductConfig();
?>
<?php if(isset($productConfigs['show_price']) && $productConfigs['show_price'] === "1"): ?>
<div id="pdc_block_layer" pdc-block="layer">
    <label data-target="#layerpricing" aria-controls="layerpricing"> <?php echo $this->__('CALCULATE ARTWORK:') ?></label>
    <!-- Example of layer. You can change html + css, but pls keep all block pdc-layer and pdc-layer-info. -->
    <div class="" id="layerpricing">
		<ul>
			<li pdc-layer="0">
				<span pdc-layer-info="type"><?php echo $this->__('ELEMENTS USED') ?></span>
				<span pdc-layer-info="price"><?php echo $this->__('Price') ?></span>
				<!--span pdc-layer-info="size"><?php echo $this->__('Size') ?></span-->
				<span pdc-layer-info="lock" data-original-title ="<?php echo $this->__('Lock|Delete layer') ?>"><i class="pdc-lock"></i><i class="pdc-unlock-alt"></i> <span><?php echo $this->__('Action') ?></span></span>
				<span pdc-layer-info="del"><i class="pdc-clear"></i> <span><?php echo $this->__('Delete') ?></span></span>
				</span>
				
			</li>
		</ul>
		<div pdc-block="layer-final" class="layer-final">
			<label><?php echo $this->__('Total Price') ?> :</label>
			<span class="price_layer"><?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->
		 getCurrentCurrencyCode())->getSymbol() ?> 0.00</span>
		</div>
    </div>
</div>
<?php endif; ?>