<?php //Social Sharing 
$is_sharing = Mage::getStoreConfig('pdp/customer_action/is_sharing');
if($is_sharing) {
?>
<div class="modal fade" id="sharingPopup" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title"><?php echo $this->__('Share your design to friends');?></h4>
	  </div>
	  <div class="modal-body">
        <div class="share-preview">
            <ul class="share-thumbnails">

            </ul>
        </div>
		<div class="share-buttons">  
            <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <!-- <a class="addthis_button_pinterest_share"></a> -->
                <a class="addthis_button_google_plusone_share"></a>
                <a class="addthis_button_email"></a>
            </div>
        </div>
        <div class="pinterest-share-thumbnail" style="position: absolute; top: -100000px; right: 100000px"></div>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5099b58f632bd3db"></script>
	  </div>
	</div>
  </div>
</div>
<?php }else{ ?>
	<div class="alert alert-warning alert-dismissible fade in" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
	  <?php echo $this->__('<strong>The sharing option is not available!</strong> Check your setting in <em>PDC configuration > Customer Actions Setting > Enable Social Sharing : Yes</em>'); ?>
	</div>
	<?php } ?>