<div class="btn-group buttons zoomcanvas">
  <a href="javascript:void(0);" pdc-zoom="in" data-toggle="tooltip" data-placement="bottom" class="btn btn-xs btn-default zoom-in" title="<?php echo $this->__('Zoom in'); ?>"><i class="pdc-search-plus"></i> <?php //echo $this->__('Zoom in'); ?></a>
  <a href="javascript:void(0);" pdc-zoom="out" data-toggle="tooltip" data-placement="bottom" class="btn btn-xs btn-default zoom-out" title="<?php echo $this->__('Zoom out'); ?>"><i class="pdc-search-minus"></i> <?php //echo $this->__('Zoom out'); ?></a>
  <!--<a href="javascript:void(0);" pdc-zoom="reset" data-toggle="tooltip" data-placement="bottom" class="btn btn-xs btn-danger eraser" title="<?php echo $this->__('Reset'); ?>"><i class="pdc-loop"></i> <?php //echo $this->__('Reset'); ?></a>-->
  <?php //Replace reset zoom function by reset design function ?>
  <a href="javascript:void(0);" pdc-action="reset_design" data-toggle="tooltip" data-placement="bottom" class="btn btn-xs btn-danger eraser" title="<?php echo $this->__('Reset'); ?>"><i class="pdc-loop"></i> <?php //echo $this->__('Reset'); ?></a>
</div>