<?php $tokenRersult = $this->getPaymentTokenResult(); ?>
<?php if($tokenRersult['succes']): ?>
    <script type="text/javascript">
        var reload = false;
        window.CKOConfig = {
            debugMode: false,
            renderMode: 2,
            namespace: 'CheckoutIntegration',
            publicKey: '<?php echo $this->getPublicKey()?>',
            paymentToken: "<?php echo $tokenRersult['token'] ?>",
            value: '<?php echo $this->getAmount() ?>',
            logoUrl: '<?php echo $this->getLightBoxUrl() ?>',
            themeColor: '<?php echo $this->getThemeColor() ?>',
            buttonColor: '<?php echo $this->getButtonColor() ?>',
            iconColor: '<?php echo $this->getIconColor() ?>',
            useCurrencyCode: '<?php echo $this->getUseCurrencyCode() ?>',
            currency: '<?php echo $this->getCurrency() ?>',
            customerEmail: '<?php echo $this->getEmailAddress() ?>',
            customerName: '<?php echo $this->getName()?>',
            paymentMode: 'mixed',
            forceMobileRedirect: true,
            title: '<?php echo $this->getStoreName(); ?>',
            subtitle:'<?php echo $this->__('Please enter your credit card details') ?>',
            widgetContainerSelector: '.payment-form',
            cardCharged: function(event){
                checkout.setLoadWaiting(false);
                if($buttonCheckout = $$('#checkout-review-submit .btn-checkout')) {

                    var eventClick = $buttonCheckout[0].show().readAttribute('data-clickEvent');
                    document.getElementById('cko-cc-paymenToken').value = event.data.paymentToken;
                    $$('#checkout-review-submit .btn-checkout')[0].writeAttribute('onclick', eventClick);
                    $('review-please-wait').show();
                   fireEvent($$('#checkout-review-submit .btn-checkout')[0], 'click');
                    $$('#checkout-review-submit .btn-checkout')[0].hide();

                    checkout.setLoadWaiting('review');

                }
            },
            paymentTokenExpired: function(){
                reload = true;
                checkout.setLoadWaiting(false);
            },
            lightboxDeactivated: function() {
                checkout.setLoadWaiting(false);
                if(reload) {
                    window.location.reload();
                }
            },
            ready: function() {

            }
        };
        if(typeof Checkout!='undefined' && Checkout.hasOwnProperty('render')) {
            Checkout.render(window.CKOConfig);
        }else if(typeof CheckoutIntegration!='undefined' && CheckoutIntegration.hasOwnProperty('render')){
            CheckoutIntegration.render(window.CKOConfig);
        }


    </script>

    <div class="payment-form"></div>

    <?php $_code=$this->getMethodCode() ?>
    <ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
        <li>
            <input type="hidden" name="payment[cko_cc_paymenToken]" id="cko-cc-paymenToken" value="<?php echo
            $this->getPaymentToken() ?>"  class="input-text "/>

            <input type="hidden" name="payment[cko_cc_redirectUrl]" id="cko-cc-redirectUrl" value=""  class="input-text "/>

        </li>
    </ul>
<?php else:  ?>
    <div style="" id="advice-required-entry-creditcard_cc_token" class="validation-advice">
        <?php echo $this->__($tokenRersult['message']) ?>
    </div>
<?php endif; ?>
<script type="text/javascript">
    if(typeof Checkout !='undefined' && Checkout.hasOwnProperty('render') && Checkout.isMobile()) {

        document.getElementById('cko-cc-redirectUrl').value = Checkout.getRedirectionUrl();
    }else   if(typeof CheckoutIntegration !='undefined' && CheckoutIntegration.hasOwnProperty('render') &&  CheckoutIntegration.isMobile()) {

        document.getElementById('cko-cc-redirectUrl').value = CheckoutIntegration.getRedirectionUrl();

    }
</script>