<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700&subset=latin,cyrillic-ext,greek-ext,latin-ext,greek,cyrillic' rel='stylesheet' type='text/css'>
<?php
    //Check able to customized or not
    /*$designBtnObj = new MST_Pdp_Block_Designbutton();
    if(!$designBtnObj) {
        return false;
    }*/
    $product = Mage::registry('current_product');
    $productId = $product->getId();
?>
<?php echo $this->getChildHtml('design_top_bar'); // Design Area Topbar (Product Title, Save, Download, Sharing) ?>
<div class="wrap_pdp_design">
	<?php echo $this->getChildHtml('product_side'); // Product Sides ?>
	<div class="pdc-design-area"> 
		<div class="pdc-design-area-left">
			<?php echo $this->getChildHtml('design_main'); //Main Design Area ?>
		</div>
		<div class="pdc-design-area-right">
			<?php echo $this->getChildHtml('design_tabs'); // Design Tabs (Add photo, Add Text, Quote, Layer ?>
		</div>
		<?php echo $this->getChildHtml('hidden_popups'); // All Hidden Actions popup ?>
		<?php echo $this->getChildHtml('layer'); ?>
	</div>
</div>

<?php /* ===NEVER CHANGE ID/CLASS == */ ?>
<div id="img_sessiton" class="nodisplay"></div>
<img alt="" id="temp_inlay_image" src="" style="display: none;"/>
<img alt="" id="temp_final_image" src="" style="display: none;"/>
<input id="temp_action" type="hidden" value=""/>
<div class="temp_container" style="display: none;"></div>
<?php $js_pdp = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'pdp/'; ?>
<!-- Preview / Download Popup -->
<div id="pdp_design_popup"></div>
<div class='pdp_actions_backend'>
	<?php //if ($this->isAdminUser()) : ?>
	<!--<link href="<?php echo $js_pdp;?>bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet"/>-->
	<!--<link href="<?php echo $js_pdp;?>bootstrap/3.3.4/css/bootstrap-theme.min.css" rel="stylesheet"/>-->
	<link href="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.pips.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/mcustomscrollbar/jquery.mcustomscrollbar.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>material-icons/style.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pace/dataurl.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>jquery/jcrop/jquery.jcrop.min.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/pdc.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/pdc.layer.css" rel="stylesheet"/>
	<link href="<?php echo $js_pdp;?>pdc/css/iframe.css" rel="stylesheet"/>
    <link href="<?php echo $js_pdp;?>instagram/css/ins.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $js_pdp;?>curvedtext/css/style.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo $js_pdp;?>jquery/colorpicker/css/colorpicker.css" rel="stylesheet"/>
	<!--<script src="<?php echo $js_pdp;?>jquery/jquery-1.10.2.min.js"></script>-->
	<!--<script src="<?php echo $js_pdp;?>bootstrap/3.3.4/js/bootstrap.min.js"></script>-->
	<script src="<?php echo $js_pdp;?>pace/pace.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/nouislider/7.1.0/jquery.nouislider.all.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/mcustomscrollbar/jquery.mcustomscrollbar.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/jcrop/jquery.jcrop.min.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/ui/jquery-ui.min.js"></script>
	<script src="<?php echo $js_pdp;?>fabricjs/fabric.js"></script>
	<script src="<?php echo $js_pdp;?>pdc/js/draggabilly.js"></script>
	<script src="<?php echo $js_pdp;?>jquery/colorpicker/colorpicker.js"></script>
    <script type="text/javascript" src="<?php echo $js_pdp;?>curvedtext/js/curvedtext.js"></script>
    <script type="text/javascript" src="<?php echo $js_pdp;?>curvedtext/js/pdc.text.action.js"></script>
	<?php //endif; ?>
</div>
<!--Loading Progess-->
<div class="pdploading" style="display: none;"><span>Please wait...</span></div>
<div id="pdp_info_to_action" class="nodisplay">
    <input type="hidden" value="<?php echo (isset($_REQUEST['fb'])) ? $_REQUEST['fb'] : "";  ?>" id="fb_get_id" />
    <input type="hidden" value="<?php echo $product->getProductUrl(); ?>" id="current_url" />
    <input type="hidden" id="product_id" name="product_id" value="<?php echo $productId; ?>" />
    <input type="hidden" value="<?php echo $this->getSkinUrl('pdp/') ?>" id="skin_url" />
	<input type="hidden" id="base_dir" name="base_dir" value="<?php echo Mage::getBaseDir('base'); ?>" />
	<input type="hidden" id="is_editable" name="is_editable" value="yes" />
	<input type="hidden" id="pdp_media_url" name="pdp_media_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'pdp/images/'; ?>" />
	<input type="hidden" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK).Mage::getStoreConfig('pdp/setting/urlkey'); ?>" id="pdp_uri_key" />
</div>
<script src="<?php echo $js_pdp;?>pdc/js/productsdesignercanvas-1.0.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc.layer.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc1.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/pdc2.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/script.js"></script>
<script src="<?php echo $js_pdp;?>pdc/js/startup.js"></script>
<script>
//Fix conflict Prototype vs Bootstrap + jQuery
if (Prototype.BrowserFeatures.ElementExtensions) {
    var disablePrototypeJS = function (method, pluginsToDisable) {
            var handler = function (event) {
                event.target[method] = undefined;
                setTimeout(function () {
                    delete event.target[method];
                }, 0);
            };
            pluginsToDisable.each(function (plugin) { 
                jQuery(window).on(method + '.bs.' + plugin, handler);
            });
        },
        pluginsToDisable = ['collapse', 'dropdown', 'modal', 'tooltip', 'popover', 'tab'];
    disablePrototypeJS('show', pluginsToDisable);
    disablePrototypeJS('hide', pluginsToDisable);
}
</script>
