<?php
    $_collection = $this->getSuggestedCollection();
?>

<?php if ($this->isEnabled() && $_collection->count() > 0): ?>
<div class="searchindex-related-terms">
    <p>
    <?php echo $this->__('Related Searches: ') ?>
    <?php foreach ($_collection as $_query): ?>
        <a href="<?php echo $this->getQueryUrl($_query) ?>"><?php echo strip_tags($_query->getQueryText()) ?></a><?php if($_query != $_collection->getLastItem()): ?>, <?php endif ?>
    <?php endforeach ?>
    </p>
</div>
<?php endif ?>