
<?php $gift_wrap_checked_user=($_POST['giftwrap']); ?>
<?php if ($this->getTotals()): ?>


  <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 4 : 3; ?>
  <?php echo $this->renderTotals(null, $_colspan); ?>
  <?php if ($gift_wrap_checked_user == 'Yes') : ?>
<?php echo $this->__('Gift Wrap');?>
<?php echo $this->helper('checkout')->formatPrice($_SESSION['price_gift_warp']);?>

  <?php 
				$_totals = Mage::getSingleton('checkout/session')->getQuote()->getGrandTotal();
				$grand_total_price_gift_wrap = ($_totals + ($_SESSION['price_gift_warp']));
			?>
<strong> <?php echo "Grand Total"; ?></strong>
<strong><?php echo $this->helper('checkout')->formatPrice($grand_total_price_gift_wrap); ?> </strong>

<?php else :?>
<?php echo $this->renderTotals('footer', $_colspan); ?>
<?php endif;?>
<?php if ($this->needDisplayBaseGrandtotal()):?>

  <small><?php echo $this->helper('sales')->__('Your credit card will be charged for') ?></small></td>
 <small><?php echo $this->displayBaseGrandtotal() ?></small>

<?php endif?>

<?php endif; ?>



