<!-- EOSide-tab-->
<div class="pdc-design-view">
<div class="pdc-main design-area">
<!-- Block main design area -->
	<div id="pdc_main_design_area">
		<?php /* ===The Main Design Area == */ ?>
		<!-- End Block side view -->
		<div class="pdc-product-image act" id="product-image-wrap">
			<div id="wrap_inlay" class="wrap_inlay"><canvas id="canvas_area"></canvas></div>
		</div>
	</div>
	
</div><!-- EODesign-area-->
<?php echo $this->getChildHtml('zoom'); ?><!-- EOSide-tab-->
<?php echo $this->getChildHtml('design_edit_tool'); ?>
<?php echo $this->getChildHtml('colors_library'); ?>
</div><!-- EODesign-view--> 