<?php 
$pcount = $this->getData('product_count');
$cat_to_select = $this->getData('category_id');
$products = $this->getRecentProducts($cat_to_select,$pcount);
//echo "<pre>";
//print_r($products);
$productMediaConfig = Mage::getModel('catalog/product_media_config');

?>
  
<tr style="width:100%;">
<td class="three-column test">
  <?php if (is_array($products) && count($products)) { ?>
    <?php 
    $i=0;
    foreach($products as $product) { 
            $thumbnailUrl  = $productMediaConfig->getMediaUrl($product['thumb']);
            $i++;
        ?>

        
                            
                                <table class="btn-newsletter" cellpadding="0" cellspacing="0" border="0" style=" width: 33%; display: inline-block; vertical-align: top; ">
                                    <tr>
                                        <td>
                                            <a href="<?php echo $product['url'] ?>" style="text-decoration:none;outline:none;"><img style="max-width:100%;width:100%;" src="<?php echo $thumbnailUrl;?>" width="261" height="303">
                                                <h5 style='background-color: #000000;
                                                    color: #ffffff;
                                                    font-family: "Roboto Condensed",sans-serif;
                                                    font-size: 23px;
                                                    font-weight: bold;
                                                    margin-top: 0;
                                                    padding-bottom: 5px;
                                                    padding-top: 5px;
                                                    text-align: center;
                                                    text-decoration: none;
                                                    text-transform: uppercase;
                                                    width: 100%;'><?php echo $product['name'] ?></h5>
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                               
                            
                            <?php
                                if($i%3==0){
                                    echo '</td></tr><tr style="width:100%;"><td class="three-column test">';
                                }
                            ?>
                        
    <?php } ?>
  <?php } ?>
</tr>