<div class="checkout-heading clearfix">
  <div class="cart-top-area clearfix">
    <h2>CHECKOUT</h2>
  </div>
</div>
<?php //echo Mage::getStoreConfig('onestepcheckout/general/title') ?>
<!-- Fill in the fields below to complete your purchase! --> 

<!-- Title description--> <?php echo Mage::getStoreConfig('onestepcheckout/general/description') ?> 
<!-- Title description-->

<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
<?php /*?> <a href="javascript:void(0)" class="onestepcheckout_loginlink" onclick='open_login();'>
            <?php echo $this->__('Already registered? Click here to login') ?>
        </a><?php */?>
<?php 
	
		//echo $this->getChildHtml('customer.login');
		//echo $this->getChildHtml('customer.forgot');
	
    }    
    ?>
<div class='ptdivline'></div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php
$seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');

$mag_version	= Mage::helper('onestepcheckout')->getMagentoVersion();
$mod_version	= Mage::helper('onestepcheckout')->getOPCVersion();

?>
<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
	var mag_ver	= '<?php echo $mag_version;?>';
	var mod_ver	= '<?php echo $mod_version;?>';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/onestepcheckout.js') ?>"></script> 
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<form action="" id="onestepcheckout_orderform" class="form-inline checkout-form">
  <?php echo $this->getChildHtml('billing.address') ?> <?php echo $this->getChildHtml('shipping.address') ?> <?php echo $this->getChildHtml('shipping.method') ?> <?php echo $this->getChildHtml('payment.method') ?>
  <?php if (Mage::getStoreConfig('onestepcheckout/general/comment')) : ?>
  <?php echo $this->helper('sales')->__('Comment') ?>
  <textarea name="order-comment" id="order-comment"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
  <?php endif; ?>
  <div class="textfix">
  <?php if (Mage::helper('onestepcheckout')->isSubscribeNewAllowed()) : ?>
  <input type="checkbox" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
  <label for="newsletter-signup"> 
  <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?> </label>
  <?php endif; ?>
  </div>
  
  <?php echo $this->getChildHtml('review') ?> 
  <?php //echo $this->getChildHtml('coupon') ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var checkout = new COGOPC('onestepcheckout_orderform', {
    	save    : '<?php echo $this->getUrl('onestepcheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onestepcheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onestepcheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");

    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		opc_window	= new COGOPC.Window({triggers: win_triggers});
    });
    jQuery(document).ready(function(){

      jQuery('#billing_customer_address').change(function(){
        if (jQuery(this).val() == '' ) {  
          clear_form_elements('bill_form');
        }
      });
       jQuery('#shipping_customer_address').change(function(){
        if (jQuery(this).val() == '' ) {
          clear_form_elements('ship_form');
        }
      });
    });
  function clear_form_elements(class_name) {
  jQuery("#"+class_name).find(':input').each(function() {
    switch(this.type) {
        case 'password':
        case 'text':
        case 'textarea':
        case 'file':
        case 'select-one':
        case 'select-multiple':
            jQuery(this).val('');
            break;
        case 'checkbox':
        case 'radio':
            this.checked = false;
    }
  });
}
//]]>
</script>
<div class="fme_loading_filters" style="display:none;"><img id="loading-image" src="<?php echo $this->getSkinUrl(); ?>images/FME/ajax-loader.gif" /></div>
<style>
        .fme_loading_filters {
            background-color: #d8d8d8;
            height: 1000%;
            left: 0;
            opacity: 0.4;
            position: absolute;
            top: 0;
            width: 100%;
            z-index: 500;
        }
        .fme_loading_filters img {
            display: block;
            left: 48%;
            position: fixed;
            top: 45%;
            z-index: 900;
        }
    </style>
<div class="container">
