<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
$jsonFilename = $buyRequest['extra_options'];
$images = Mage::helper('pdp')->getThumbnailImage($jsonFilename);
if(empty($images)) {
	return;
}
?>
<dt><span style="font-weight: bold"><?php echo $this->__('Customize Design') ?></span></dt>
<dl class="item-options">
<?php foreach ($images as $image) : ?>
	<dt><?php echo $this->__($image['name']) ?></dt>
	<dd><img src="<?php echo $image['image'] ?>" width="100" alt="<?php echo $this->__('Customized Image') ?>"/></dd>
<?php endforeach; ?>
</dl>



