<?php
/**
 * Yireo GoogleTranslate for Magento
 *
 * @package     Yireo_GoogleTranslate
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2015 Yireo (http://www.yireo.com/)
 * @license     Open Software License
 */
?>
<script type="text/javascript">
    YireoGoogleTranslate.ajaxEntityBaseUrl = '<?= $this->getAjaxEntityBaseUrl(); ?>';
    YireoGoogleTranslate.ajaxTextBaseUrl = '<?= $this->getAjaxTextBaseUrl(); ?>';
</script>