<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2012 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.4
 */
?>
<?php
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="grid">
	<div class="grid_4 alpha">
		<h3><?php echo $this->__('Sign In') ?></h3>
		
		<form id="login-form" class="stack-form" action="<?php echo $this->getPostAction() ?>" method="post">
			<ul class="form-list">
				<li>
					<label for="login-email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
					
					<div class="input-box">
    					<input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" title="<?php echo $this->__('Email') ?>" />
    				</div>
				</li>
				
				<li>
					<label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
					
					<div class="input-box">
				    	<input type="password" class="input-text required-entry" id="login-password" name="login[password]" title="<?php echo $this->__('Password') ?>" />
				    </div>
				</li>
				
				<?php echo $this->getChildHtml('form.additional.info'); ?>
				<?php echo $this->getChildHtml('persistent.remember.me'); ?>
			</ul>
			
			<div class="buttons-set">
			    <button type="submit" class="button"><?php echo $this->__('Sign In') ?></button>
			    <a class="alt-action" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
			</div>
			
			<input name="context" type="hidden" value="checkout" />
		</form>

        <?php if(Mage::helper('pslogin')->modulePositionEnabled('login') && Mage::helper('pslogin')->hasButtons()) : ?>
            <div class="pslogin-spacer pslogin-clearfix"> 
                <table>
                    <tr>
                        <td><div class="pslogin-border"></div></td>
                        <td class="pslogin-bordertext w25"><?php echo $this->__('OR'); ?></td>
                        <td><div class="pslogin-border"></div></td>
                    </tr>
                </table>
            </div>
            <?php echo $this->getChildHtml('pslogin_buttons'); ?>
        <?php endif; ?>
	</div>

	<div class="grid_3 omega">
		<h3><?php echo $this->__('Create An Account') ?></h3>
		
		<div class="stack-form">
    		<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
    			<ul class="form-list">
    				<li class="control">
    					<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" />
    					<label for="login:register"><?php echo $this->__('Register and checkout together') ?></label>
    				</li>
    			</ul>
    			
    			<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
    				<h3><?php echo $this->__('Guest Checkout') ?></h3>
    				
    				<ul class="form-list">
    				    <li class="control">
    						<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" />
    						<label for="login:guest"><?php echo $this->__('Checkout without registering') ?></label>
    				    </li>
    				</ul>
    			<?php endif; ?>
    		<?php else: ?>
    			<input type="hidden" name="checkout_method" id="login:register" value="register" />
    		<?php endif; ?>
    		
    		<div class="buttons-set">
        		<?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
        		    <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><?php echo $this->__('Continue') ?></button>
        		<?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
	                <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><?php echo $this->__('Register') ?></button>
        		<?php else: ?>
        		    <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
        		        <button id="onepage-guest-register-button" type="submit" class="button"><?php echo $this->__('Register') ?></button>
        		    </form>
        		<?php endif; ?>
    		</div>
    	</div>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>

<?php $registerParam = $this->getRequest()->getParam('register'); ?>
<?php if ($registerParam || $registerParam === ''): ?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
