<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>


<?php
$helper = Mage::helper('pslogin');
if(!$helper->moduleEnabled()) {
    return;
}
?>

<script type="text/javascript">
	psloginLoginPath = "<?php echo addslashes(Mage::getUrl('pslogin/account/login')); ?>";
	customerLogoutPath = "<?php echo addslashes(Mage::getUrl('customer/account/logout')); ?>";
</script>