<div id="payment-method" class="onestepcheckout_block">
  <div class="page-header checkout-form-headings paymentmethod-heading">
    <h1>
      <div class="skewed"><span class="re-skewed"><?php echo $this->__('3. payment') ?></span></div>
    </h1>
  </div>
  <div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
  </div>
  <script type="text/javascript">
    //<![CDATA[
        function toggleToolTip(event){
            if($('payment-tool-tip')){
                $('payment-tool-tip').setStyle({
                    top: (Event.pointerY(event)-300)+'px',
                    left: (Event.pointerX(event)-200)+'px'
                });
                $('payment-tool-tip').toggle();
            }
            Event.stop(event);
        }
        if($('payment-tool-tip-close')){
            Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
        }
        var payment = new Payment('payment-method');
    //]]>
    </script>
  <div id="checkout-payment-method-load"> <?php echo $this->getChildHtml('methods') ?> </div>
  <script type="text/javascript">
    //<![CDATA[
        payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
    </script> 
</div>
