<?php
    Mage::register('chart_package', 'corechart');
    $_currencyFormat = Mage::getSingleton('advr/config')->getCurrencyFormat();
?>

<script type="text/javascript">
    function drawChart() {
        var data = google.visualization.arrayToDataTable(<?php echo json_encode($this->getDataTable()) ?>);

        var formatter = new google.visualization.NumberFormat({pattern: '<?php echo $_currencyFormat ?>'});
        <?php foreach ($this->getColumnTypes() as $_idx => $_type): ?>
            <?php if ($_type == 'currency'): ?>
            formatter.format(data, <?php echo $_idx + 1 ?>);
            <?php endif ?>
        <?php endforeach ?>

        if (data.getNumberOfRows() == 0) {
            document.getElementById('chart_div').style.display = 'none';
            document.getElementById('export_link').style.display = 'none';
            
            return;
        }

        var defaultSeries = <?php echo json_encode($this->getDefaultSeries()) ?>;

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

        var columns = [];

        var series = {};
        for (var i = 0; i < data.getNumberOfColumns(); i++) {
            if (i == 0 || defaultSeries.indexOf(i) > -1) {
                columns.push(i);
            } else {
                columns.push({
                    label: data.getColumnLabel(i),
                    type: data.getColumnType(i),
                    sourceColumn: i,
                    calc: function () {
                        return null;
                    }
                });
                series[i - 1] = {type: "line"};
            }

            if (i > 0) {
                if (series[i - 1] == undefined) {
                    series[i - 1] = {};
                }

                if (defaultSeries.indexOf(i) == -1) {
                    series[i - 1].color = '#eeeeee';
                }
            }
        }

        var options = {
            series: series,

            chartArea: {
                width: '100%',
                height: '70%'
            },
            
            bar: {
                groupWidth: '95%'
            },

            bars: 'vertical',

            colors: <?php echo json_encode($this->getColumnColors()) ?>,
            // colors: ["#2fd75b", "#ff7e0e", "#52c4ff", "#c7b700", "#aaeeee", "#ff0066", "#eeaaee", "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
            
            fontSize: '11',

            legend: {
                position: 'bottom',
                alignment: 'center',
                textStyle: {
                    color    : '#aaaaaa',
                    fontSize : '11'
                }
            },
            hAxis: {
                textStyle: {
                    color    : '#aaaaaa',
                    fontSize : '11'
                },
                slantedText: false,
                maxAlternation: 1
            },
            vAxis: {
                textPosition: 'in',
                baselineColor: '#dddddd',
                gridlines: {
                    color: '#f0f0f0'
                },
                textStyle: {
                    color    : '#aaaaaa',
                }
            }
        }

        function showHideSeries() {
            var sel = chart.getSelection();
            if (sel.length > 0) {
                if (sel[0].row == null) {
                    var col = sel[0].column;
                    if (typeof(columns[col]) == 'number') {
                        var src = columns[col];

                        // hide the data series
                        columns[col] = {
                            label: data.getColumnLabel(src),
                            type: data.getColumnType(src),
                            sourceColumn: src,
                            calc: function () {
                                return null;
                            }
                        };

                        series[src - 1].color = '#eeeeee';
                        series[src - 1].type  = 'line';
                    } else {
                        var src = columns[col].sourceColumn;
                        columns[col] = src;

                        series[src - 1].color = null;
                        series[src - 1].type  = 'column';
                    }
                    var view = new google.visualization.DataView(data);
                    view.setColumns(columns);
                    chart.draw(view, options);
                }
            }
        }
        
        google.visualization.events.addListener(chart, 'select', showHideSeries);

        google.visualization.events.addListener(chart, 'ready', function () {
            export_link.href = chart.getImageURI();
        });

        var view = new google.visualization.DataView(data);
        
        view.setColumns(columns);

        chart.draw(view, options);
    }
</script>

<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;">Save chart as an image</a>
<div id="chart_div" style="widht: 100%; height: 400px;"></div>