<?php
    Mage::register('chart_package', 'geochart');
    $_currencyFormat = Mage::getSingleton('advr/config')->getCurrencyFormat();
?>
<script type="text/javascript">
    function drawChart()
    {   
        var data = new google.visualization.DataTable();

        <?php foreach ($this->getColumns() as $column): ?>
        data.addColumn('<?php echo $column->getType() ?>', '<?php echo $column->getLabel() ?>');
        <?php endforeach ?>
        
        data.addRows(<?php echo json_encode($this->getSeries()) ?>);

        var formatter = new google.visualization.NumberFormat({pattern: '<?php echo $_currencyFormat ?>'});
        formatter.format(data, 1);

        var options = <?php echo $this->getOptionsAsJson() ?>;

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));

        google.visualization.events.addListener(chart, 'ready', function () {
            export_link.href = chart.getImageURI();
        });

        chart.draw(data, options);

        function clickHandler()
        {  
            var selection = chart.getSelection();
            var message = '';
            for (var i = 0; i < selection.length; i++) {
                var item = selection[i];
                if (item.row != null) {
                    // alert(data.getValue(item.row, 0));
                }
            }
        }

        google.visualization.events.addListener(chart, 'select', clickHandler);
    }
</script>

<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;">Save chart as an image</a>
<div id="chart_div" style="widht: 100%; height: 500px;"></div>