<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>

<script type="text/javascript">
function drawChart()
{
    var data = {};

    <?php foreach ($this->getSeries() as $idx => $itm): ?>
        data[<?php echo $idx ?>] = {
            center: new google.maps.LatLng(<?php echo $itm[0] ?>, <?php echo $itm[1] ?>),
            label: "<?php echo addslashes($itm['label']) ?>",
        };
    <?php endforeach ?>

    // var options = <?php echo $this->getOptionsAsJson() ?>;
    var options = {
        mapTypeId: google.maps.MapTypeId.TERRAIN,
        zoom: 3,
        center: new google.maps.LatLng(40, 0),
    };

    // console.log(JSON.stringify(options));

    var map = new google.maps.Map(document.getElementById('chart_div'), options);

    // geocoder = new google.maps.Geocoder();

    infowindow = new google.maps.InfoWindow({
        content: "holding..."
    });

    var latLngList = new Array();// (new google.maps.LatLng (52.537,-2.061), new google.maps.LatLng (52.564,-2.017));
    for (var idx in data) {
        var item = data[idx];
        latLngList.push(item.center);
        // var valueOptions = {
        //   strokeColor: '#0000ff',
        //   // strokeOpacity: 0.8,
        //   strokeWeight: 0,
        //   fillColor: '#0000ff',
        //   fillOpacity: 0.35,
        //   map: map,
        //   center: data[item].center,
        //   radius: Math.sqrt(data[item].value) * 10000
        // };

        // itemCircle = new google.maps.Circle(valueOptions);

        // data[item].infowindow = new google.maps.InfoWindow({
        //     content: data[item].value + ' '
        // });
        var marker = new google.maps.Marker({
            position : item.center,
            map      : map,
            label    : item.label
        });
        google.maps.event.addListener(marker, 'click', function () {
            console.log(this.label);
            infowindow.setContent(this.label);
            infowindow.open(map, this);
        });

        // google.maps.event.addListener(item.marker, 'click', function(e) {
        //     console.log(e);
        //     data[item].infowindow.open(map, data[item].marker);
        // });
    }

    // center and zoom map based on markers
    var bounds = new google.maps.LatLngBounds ();
    for (var i = 0, LtLgLen = latLngList.length; i < LtLgLen; i++) {
        bounds.extend (latLngList[i]);
    }
    map.fitBounds(bounds);
}

google.maps.event.addDomListener(window, 'load', drawChart);
</script>

<div id="chart_div" style="widht: 100%; height: 500px;"></div>