<?php
    Mage::register('chart_package', 'corechart');
    $_currencyFormat = Mage::getSingleton('advr/config')->getCurrencyFormat();
?>

<script type="text/javascript">
    function drawChart()
    {
        var data = google.visualization.arrayToDataTable(<?php echo json_encode($this->getSeries()) ?>);

        var formatter = new google.visualization.NumberFormat({pattern: '<?php echo $_currencyFormat ?>'});
        formatter.format(data, 1);

        if (data.getNumberOfRows() == 0) {
            document.getElementById('chart_div').style.display = 'none';
            document.getElementById('export_link').style.display = 'none';
            return;
        }
        
        var options = {
            // is3D: true,
            pieHole: 0.2,

            chartArea: {
                width: '100%',
                height: '85%'
            },

            colors: ["#2fd75b", "#ff7e0e", "#52c4ff", "#c7b700", "#aaeeee", "#ff0066", "#eeaaee", "#55BF3B", "#DF5353", "#7798BF", "#aaeeee"],
            
            fontSize: '11',

            legend: {
                position: 'bottom',
                alignment: 'center',
                textStyle: {
                    color    : '#aaaaaa',
                    fontSize : '11'
                }
            }
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));

        google.visualization.events.addListener(chart, 'ready', function () {
            export_link.href = chart.getImageURI();
        });

        chart.draw(data, options);
    }
</script>

<a id="export_link" target="_blank" style="float:right; z-index: 10000;position:relative;">Save chart as an image</a>
<div id="chart_div" style="widht: 100%; height: 400px;"></div>