<?php echo $this->getChildHtml('items_before'); ?>
<div class="cart-table-area checkout-table">
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery("#checkout-review-table").stacktable();
});
</script>
    <table class="order-products-table" id="checkout-review-table" cellpadding="10" cellspacing="10">
        <col />
        <col width="1" />
        <col width="1" />
        <?php
        $colspan	= 1;
        if ($this->helper('tax')->displayCartBothPrices()):
        	$colspan= 2;
        ?>
        <col width="1" />
        <?php endif; ?>
      <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo $this->__('Image') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
                <th class="a-right" colspan="<?php echo $colspan ?>"><?php echo $this->__('Subtotal') ?></th>
                <th><?php echo $this->__('Remove') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
    
    
    
      <div class="cart-btn-area checkout-payment-total clearfix">
        <div class="btn-holder"> 
         <?php echo $this->getChildHtml('totals'); ?>
        
        </div>
      </div>
    
    
    
</div>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
