<?php
$helper = Mage::helper('pdp');
$fonts = $helper->getFonts();
?>
<style type="text/css">
    <?php foreach ( $fonts as $font) { ?>
    @font-face {
        font-family: '<?php echo $font->getName() ?>';
        src: url('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>pdp/fonts/<?php echo $font->getName() ?>.<?php echo $font->getExt() ?>');
    }
    <?php } ?>
</style> 