<?php 
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'pdp/shapes/';
	$baseUrl = Mage::helper("pdp")->getPdpBaseUrl();
	$categoryOptions = Mage::getModel('pdp/shapecate')->getCategoryOptions();
?>
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-8"> 
                    <h3 class="panel-title">Manage Shapes</h3>
                </div>
                <div class="col-md-4">
                    <div class="pull-right">
                        <div class="btn-group">
                            <a type="button" class="btn btn-warning btn-md" data-toggle="modal" data-target="#upload-files-form">Add New Shape</a>
                            <a class="btn btn-success">Action</a>
                            <a data-toggle="dropdown" class="btn btn-success dropdown-toggle">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a id="select_item" href="#">Select Item(s)</a></li>
                                <li><a id="select_all_item" href="#">Select All Items</a></li>
                                <li><a id="uncheck_all_item" href="#">Unchecked All Items</a></li>
                                <li class="divider"></li>
                                <li><a id="delete_selected_shape" href="#">Delete Selected Item(s)</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="alert alert-info">
                <p>
                    <strong>NOTE!</strong> Input shape name or tag have meaningful for search purpose!
                </p>
                <p>
                    <strong>Tip!</strong> To change the shape name or tag, please press <strong>ENTER</strong> after input info!
                </p>
            </div>
            <div id="shape-manage">
                <div class="mst_pagination">
                    <input type="hidden" value="<?php echo $baseUrl ?>" name="base_url" id="base_url"/>
                    <input type="hidden" value="<?php echo $mediaUrl ?>" name="media_url" id="media_url"/>
                    <?php
                    # Paging a collection
                    echo "<input type='hidden' name='current_page' value='1'>";
                    echo "<input type='hidden' name='page_size' value='". $this->_default_page_size ."'>";
                    $paging_collection = $this->getImageCollectionPaging(1, $this->_default_page_size, 'pdp/shape/getImagePaging', '0');
                    $imageList = $paging_collection['collection'];
                    echo $paging_collection['paging_text'];
                    # End paging a collection
                    ?>
                </div>
                <div class="tab-content">
                    <div class="tab-pane active" id="image">
                        <div class='image-contianer'>
                            <input type='hidden' name='secret_key' id='secret_key' value='<?php echo Mage::helper("adminhtml")->getUrl("pdpadmin/adminhtml_pdp/artworkcolorinfo/"); ?>'/>
                            <div id='container' class="clickable clearfix">
                                <div class="row">
                                    <?php foreach ($imageList as $image) :?>
                                    <div class="col-sm-4 col-md-2">
                                        <div class="thumbnail">
                                             <img src='<?php echo $mediaUrl . $image->getFilename() ?>' alt='' width="100px" />
                                            <div class="caption">
                                                <div class="form-group">
                                                    <label for="shape_<?php echo $image->getId() ?>"><?php echo $this->__("Shape Name") ?></label>
                                                    <?php $shapeName = str_replace(".svg", "", $image->getOriginalFilename()) ?>
                                                    <input type="text" class="form-control shape-name" value="<?php echo $shapeName ?>" id="shape_<?php echo $image->getId() ?>">
                                                </div>
                                                <div class="form-group">
                                                    <label for="shapetag_<?php echo $image->getId() ?>"><?php echo $this->__("Tags") ?></label>
                                                    <input type="text" class="form-control shape-tag" value="<?php echo $image->getTag() ?>" id="shapetag_<?php echo $image->getId() ?>">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <input type="hidden" value="<?php echo $baseUrl ?>" name="base_url" id="base_url"/>
                <!--Upload clipart modal-->
                <div class="modal fade" id="upload-files-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <a class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></a>
                                <h4 class="modal-title" id="myModalLabel">Upload Shapes</h4>
                            </div>
                            <div class="modal-body">
                                <div class="alert alert-info">
                                    <p class='support-files'>Supported Shape Formats : <b>.svg</b> only</p>
                                    <p class='support-files'>Allow uploading multiple files!</p>
                                </div>
                                <form class="form-horizontal" id="upload_shape_form" name="upload_shape_form" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl("pdpadmin/adminhtml_shape/upload"); ?>" method="POST">
                                    <input type="hidden" name="upload_file_type" value="custom" id="upload_file_type"/>
                                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                                    <input type="hidden" id="base_dir" name="base_dir" value="<?php echo Mage::getBaseDir(); ?>" />
                                    <input type="hidden" id="skin_url" name="skin_url" value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>" />
                                    <div class="form-group">
                                        <label for='tag' class="col-sm-3 control-label">Shape Tag</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="tag" id="shape_tag" />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for='image_category' class="col-sm-3 control-label">Choose Clipart Category</label>
                                        <div class="col-sm-9">
                                            <select id='image_category' name='category' class="form-control">
                                                <?php 
                                                $options = $categoryOptions;
                                                foreach ($options as $key => $value) {
                                                    echo "<option value='". $key ."'>{$value}</option>";
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for='filename' class="col-sm-3 control-label"></label>
                                        <div class="col-sm-9">
                                            <input type="file" accept="image/svg+xml" name="shapes[]" id="shape" multiple/>
                                        </div>
                                    </div>
                                     <div class="form-group">
                                        <label for='filename' class="col-sm-3 control-label"></label>
                                        <div class="col-sm-9">
                                            <input type="submit" value="Upload" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
//Fix conflict Prototype vs Bootstrap + jQuery
if (Prototype.BrowserFeatures.ElementExtensions) {
    var disablePrototypeJS = function (method, pluginsToDisable) {
            var handler = function (event) {
                event.target[method] = undefined;
                setTimeout(function () {
                    delete event.target[method];
                }, 0);
            };
            pluginsToDisable.each(function (plugin) { 
                jQuery(window).on(method + '.bs.' + plugin, handler);
            });
        },
        pluginsToDisable = ['collapse', 'dropdown', 'modal', 'tooltip', 'popover'];
    disablePrototypeJS('show', pluginsToDisable);
    disablePrototypeJS('hide', pluginsToDisable);
}
</script>