<div class="row">
  <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h2>Track your shipments </h2>
  </div>
</div>
<div class="row">
  <div class="faq-area bulk-area col col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <form id="shipment_track_frm" class="bulk-order-form track-shipment-form" action="" method="get" name="shipment_track_frm">
      <div class="form-row">
        <div class="form-select-col">
          <label for="country">*Shipment</label>
          <span class="fake-select">
          <select id="shipment" name="shipment">
            <option title="Speedex" value="speedex">Speedex</option>
            <option title="Fedex" value="fedex">Fedex</option>
          </select>
          </span></div>
        <div class="form-select-col second-child">
          <label for="city">*Tracking number</label>
          <input id="tracking_number" class="required-entry" type="text" placeholder="Please enter tracking number" name="tracking_number" />
        </div>
        <div class="form-select-col third-child">
          <input type="button" value="SUBMIT" onclick="return loadIframe('ifrm');" />
        </div>
      </div>
      <!-- <div class="form-row">
        <div class="form-textarea-col">
          <input type="button" value="SUBMIT" onclick="return loadIframe('ifrm');" />
        </div>
      </div> -->
      <div class="" id="iframdiv" style="display:none;">
        <iframe name="ifrm" id="ifrm" src="" frameborder="0" width="1100" height="520" scrolling="yes"></iframe>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">// <![CDATA[
//< ![CDATA[
  var myForm= new VarienForm('shipment_track_frm', true);
// ]]></script> 
<script type="text/javascript">
function loadIframe(iframeName) {
	var ship_val = jQuery('#shipment').val();
	var tracking_number = jQuery('#tracking_number').val();
	jQuery('#iframdiv').show();
	if(ship_val=='speedex'){
		var url = 'https://ws01.ffdx.net/v4/login.aspx?stid=postaplus&css=postaplus';
	}else{
		var url = 'https://www.fedex.com/apps/fedextrack/?action=track&trackingnumber='+tracking_number;
	}
    var $iframe = jQuery('#' + iframeName);
    if ( $iframe.length ) {
        $iframe.attr('src',url);   
        return false;
    }
    return true;
}
</script>