<?php
/**
 * MageWorx
 * Admin Order Editor extension
 *
 * @category   MageWorx
 * @package    MageWorx_OrdersEdit
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */

$_order = $this->getOrder();
?>
<div class="hor-scroll">
    <table cellspacing="0" class="form-list">
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Name') ?></label></td>
            <td class="value">
                <?php if ($_customerUrl=$this->getCustomerViewUrl()) : ?>
                    <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->escapeHtml($_order->getCustomerName()) ?></strong></a>
                <?php else: ?>
                    <strong><?php echo $this->escapeHtml($_order->getCustomerName()) ?></strong>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td class="label"><label><?php echo Mage::helper('sales')->__('Email') ?></label></td>
            <td class="value"><a href="mailto:<?php echo $_order->getCustomerEmail() ?>"><strong><?php echo $_order->getCustomerEmail() ?></strong></a></td>
        </tr>
        <?php if ($_groupName = $this->getCustomerGroupName()) : ?>
            <tr>
                <td class="label"><label><?php echo Mage::helper('sales')->__('Customer Group') ?></label></td>
                <td class="value"><strong><?php echo $_groupName ?></strong></td>
            </tr>
        <?php endif; ?>
        <?php foreach ($this->getCustomerAccountData() as $data):?>
            <tr>
                <td class="label"><label><?php echo $data['label'] ?></label></td>
                <td class="value"><strong><?php echo $data['value'] ?></strong></td>
            </tr>
        <?php endforeach;?>
    </table>
</div>